-- ============================================================================
-- digital-menu-platform — Baseline schema migration
-- Generated: 2026-08-05
--
-- SOURCE OF TRUTH: this file was NOT written by hand-editing the old loose
-- SQL scripts in supabase/. It was generated by directly introspecting the
-- LIVE production database (Supabase project qr-menu-platform,
-- rfugdsubimdlakmvqyjm) via `pg_catalog`/`information_schema` — every
-- column, default, constraint, index, and RLS policy below was verified to
-- match what is actually running in production as of the date above.
--
-- This is the FIRST migration for this project. Supabase's own migration
-- history table (`supabase_migrations.schema_migrations`) is currently
-- EMPTY — meaning the live schema was built entirely by hand via the SQL
-- Editor over time, with no tracked migration history. This file is the
-- starting point for tracked migrations going forward. It intentionally
-- reproduces the CURRENT live schema exactly (including its quirks, noted
-- inline below) rather than a "cleaned up" version — cleanup is separate,
-- deliberate, future work, not silently bundled into this consolidation.
--
-- Running this file against a FRESH Supabase project reproduces the current
-- production schema. Running it against THIS project again is safe — every
-- statement is idempotent (IF NOT EXISTS / DROP POLICY IF EXISTS).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------
-- Live project also has pgcrypto, pg_stat_statements, and supabase_vault
-- enabled — these are Supabase platform defaults, not something this app's
-- schema depends on directly, so they are not created here.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------------
-- Table: stores
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.stores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  logo_url text,
  banner_url text,
  primary_color text DEFAULT '#111827',
  secondary_color text DEFAULT '#f59e0b',
  phone text,
  email text,
  address text,
  description text,
  status text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'archived')),
  created_at timestamptz NOT NULL DEFAULT now(),
  hero_image_url text,
  welcome_title text,
  welcome_subtitle text,
  welcome_button_text text,
  show_welcome_screen boolean NOT NULL DEFAULT false,
  default_content_language text NOT NULL DEFAULT 'ar',
  welcome_title_ar text,
  welcome_title_he text,
  welcome_title_en text,
  welcome_subtitle_ar text,
  welcome_subtitle_he text,
  welcome_subtitle_en text,
  welcome_button_text_ar text,
  welcome_button_text_he text,
  welcome_button_text_en text,
  menu_background_url text,
  whatsapp_number text
);

COMMENT ON COLUMN public.stores.hero_image_url IS 'Alternate full-screen background if banner_url is empty';
COMMENT ON COLUMN public.stores.welcome_title IS 'Headline on welcome intro at /{slug}';
COMMENT ON COLUMN public.stores.welcome_subtitle IS 'Welcome message on intro screen';
COMMENT ON COLUMN public.stores.welcome_button_text IS 'Legacy custom CTA (app uses fixed Start Now labels)';
COMMENT ON COLUMN public.stores.show_welcome_screen IS 'Legacy flag; public /{slug} always shows welcome intro';
COMMENT ON COLUMN public.stores.menu_background_url IS 'Full-screen background for public menu categories page';
COMMENT ON COLUMN public.stores.default_content_language IS 'Owner input language: ar | he | en';

-- NOTE (drift found during this consolidation, 2026-08-05):
-- `description` and the `status` CHECK constraint exist in production but
-- were never present in ANY committed SQL file before this one. They were
-- added directly in the Supabase SQL Editor at some point and never
-- backfilled into the repo. `show_welcome_screen` also defaults to `false`
-- live, while the old store-welcome-columns.sql claimed `DEFAULT true` —
-- a direct contradiction between the file and reality. This file matches
-- what is REALLY running.

-- ---------------------------------------------------------------------------
-- Table: profiles
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY,
  full_name text,
  role text NOT NULL DEFAULT 'store_owner'
    CHECK (role IN ('super_admin', 'store_owner')),
  store_id uuid REFERENCES public.stores (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- NOTE (drift found during this consolidation, 2026-08-05):
-- The old base-schema.sql declared `id uuid PRIMARY KEY REFERENCES
-- auth.users (id) ON DELETE CASCADE`. Production has NO such foreign key —
-- `profiles.id` is a bare UUID primary key with zero referential integrity
-- against `auth.users`. In practice `id` is always set to the signed-in
-- user's `auth.uid()` by application code, so this has not caused a visible
-- bug, but it means: (1) deleting an Auth user does NOT cascade-delete
-- their profile row (orphaned profiles are possible), and (2) nothing in
-- the database itself prevents a profile row with an id that doesn't match
-- any real Auth user. This file reproduces the CURRENT (unconstrained)
-- reality rather than silently re-adding the FK, because adding it back
-- is a real behavior change (a DDL migration against live data with 2
-- existing profile rows) that deserves its own reviewed task, not to be
-- smuggled into a "just reorganize the files" consolidation. Flagged
-- below as a new follow-up task (1.12).

-- ---------------------------------------------------------------------------
-- Table: menu_categories
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.menu_categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES public.stores (id) ON DELETE CASCADE,
  name text NOT NULL,
  slug text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  name_ar text,
  name_he text,
  name_en text,
  UNIQUE (store_id, slug)
);

-- ---------------------------------------------------------------------------
-- Table: menu_items
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.menu_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  store_id uuid NOT NULL REFERENCES public.stores (id) ON DELETE CASCADE,
  category_id uuid REFERENCES public.menu_categories (id) ON DELETE CASCADE,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  price numeric NOT NULL DEFAULT 0,
  image_url text,
  is_active boolean NOT NULL DEFAULT true,
  is_featured boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  name_ar text,
  name_he text,
  name_en text,
  description_ar text,
  description_he text,
  description_en text,
  original_price numeric,
  UNIQUE (store_id, slug)
);

COMMENT ON COLUMN public.menu_items.original_price IS 'Original price before discount. If set, item appears in Offers section.';

-- NOTE: `menu_items.category_id` is ON DELETE CASCADE in production (not
-- ON DELETE SET NULL as the old base-schema.sql claimed). Reproduced as-is.

-- ---------------------------------------------------------------------------
-- Table: pending_signups
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.pending_signups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  restaurant_name text NOT NULL,
  email text NOT NULL,
  whatsapp text NOT NULL,
  plan text NOT NULL
    CHECK (plan IN ('basic', 'pro', 'premium', 'small', 'medium', 'large')),
  notes text,
  estimated_items text,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),
  approved_store_id uuid REFERENCES public.stores (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- NOTE: production's default for `pending_signups.id` is
-- `extensions.uuid_generate_v4()` (the old uuid-ossp extension, schema-
-- qualified). This file uses `gen_random_uuid()` instead — Postgres's
-- built-in generator, already used by all 3 other UUID-PK tables — so a
-- FRESH project created from this file doesn't need the uuid-ossp
-- extension enabled for this table either. This is a deliberate, safe
-- normalization for NEW environments only; it does not touch the live
-- default in production (changing a column default is a no-op for existing
-- rows and has no behavioral effect either way — both functions produce a
-- valid random UUID).

-- ---------------------------------------------------------------------------
-- Row Level Security — profiles
-- ---------------------------------------------------------------------------

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON public.profiles;
CREATE POLICY "profiles_select_own"
  ON public.profiles FOR SELECT TO authenticated
  USING (auth.uid() = id);

-- ---------------------------------------------------------------------------
-- Row Level Security — store owner access
-- ---------------------------------------------------------------------------

ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "menu_categories_owner_select" ON public.menu_categories;
CREATE POLICY "menu_categories_owner_select"
  ON public.menu_categories FOR SELECT TO authenticated
  USING (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_categories_owner_insert" ON public.menu_categories;
CREATE POLICY "menu_categories_owner_insert"
  ON public.menu_categories FOR INSERT TO authenticated
  WITH CHECK (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_categories_owner_update" ON public.menu_categories;
CREATE POLICY "menu_categories_owner_update"
  ON public.menu_categories FOR UPDATE TO authenticated
  USING (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_categories_owner_delete" ON public.menu_categories;
CREATE POLICY "menu_categories_owner_delete"
  ON public.menu_categories FOR DELETE TO authenticated
  USING (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_items_owner_select" ON public.menu_items;
CREATE POLICY "menu_items_owner_select"
  ON public.menu_items FOR SELECT TO authenticated
  USING (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_items_owner_insert" ON public.menu_items;
CREATE POLICY "menu_items_owner_insert"
  ON public.menu_items FOR INSERT TO authenticated
  WITH CHECK (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_items_owner_update" ON public.menu_items;
CREATE POLICY "menu_items_owner_update"
  ON public.menu_items FOR UPDATE TO authenticated
  USING (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "menu_items_owner_delete" ON public.menu_items;
CREATE POLICY "menu_items_owner_delete"
  ON public.menu_items FOR DELETE TO authenticated
  USING (store_id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "stores_owner_select" ON public.stores;
CREATE POLICY "stores_owner_select"
  ON public.stores FOR SELECT TO authenticated
  USING (id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

DROP POLICY IF EXISTS "stores_owner_update" ON public.stores;
CREATE POLICY "stores_owner_update"
  ON public.stores FOR UPDATE TO authenticated
  USING (id IN (SELECT store_id FROM public.profiles WHERE id = auth.uid() AND store_id IS NOT NULL));

-- ---------------------------------------------------------------------------
-- Row Level Security — public menu reads
-- ---------------------------------------------------------------------------

DROP POLICY IF EXISTS "stores_public_select_active" ON public.stores;
CREATE POLICY "stores_public_select_active"
  ON public.stores FOR SELECT TO anon, authenticated
  USING (status = 'active');

DROP POLICY IF EXISTS "menu_categories_public_select_active" ON public.menu_categories;
CREATE POLICY "menu_categories_public_select_active"
  ON public.menu_categories FOR SELECT TO anon, authenticated
  USING (is_active = true AND store_id IN (SELECT id FROM public.stores WHERE status = 'active'));

DROP POLICY IF EXISTS "menu_items_public_select_active" ON public.menu_items;
CREATE POLICY "menu_items_public_select_active"
  ON public.menu_items FOR SELECT TO anon, authenticated
  USING (is_active = true AND store_id IN (SELECT id FROM public.stores WHERE status = 'active'));

-- ---------------------------------------------------------------------------
-- Row Level Security — pending_signups
-- ---------------------------------------------------------------------------

ALTER TABLE public.pending_signups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "signups_admin_all" ON public.pending_signups;
CREATE POLICY "signups_admin_all"
  ON public.pending_signups FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'super_admin'));

DROP POLICY IF EXISTS "signups_public_insert" ON public.pending_signups;
CREATE POLICY "signups_public_insert"
  ON public.pending_signups FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- ============================================================================
-- End of baseline. Every future schema change ships as a new file in
-- supabase/migrations/, named YYYYMMDDHHMMSS_short_description.sql.
-- ============================================================================